import { z } from "zod";

export enum EReasonCode {
    'ASA' = 'ASA',
    'NewDEV' = 'NewDEV',
    'NULL_NA' = 'NULL_NA',
    'FTTB_C' = 'FTTB_C',
    'FTTB_CT' = 'FTTB_CT',
    'FTTB_NS' = 'FTTB_NS',
    'FTTB_SA' = 'FTTB_SA',
    'FTTB_NA' = 'FTTB_NA',
    'FTTC_C' = 'FTTC_C',
    'FTTC_CT' = 'FTTC_CT',
    'FTTC_NS' = 'FTTC_NS',
    'FTTC_SA' = 'FTTC_SA',
    'FTTN_C' = 'FTTN_C',
    'FTTN_CT' = 'FTTN_CT',
    'FTTN_NS' = 'FTTN_NS',
    'FTTN_SA' = 'FTTN_SA',
    'FTTN_NA' = 'FTTN_NA',
    'FTTP_C' = 'FTTP_C',
    'FTTP_CT' = 'FTTP_CT',
    'FTTP_NS' = 'FTTP_NS',
    'FTTP_SA' = 'FTTP_SA',
    'FTTP_NA' = 'FTTP_NA',
    'FW_C' = 'FW_C',
    'FW_CT' = 'FW_CT',
    'FW_NA' = 'FW_NA',
    'FW_NS' = 'FW_NS',
    'FW_SA' = 'FW_SA',
    'HFC_C' = 'HFC_C',
    'HFC_CT' = 'HFC_CT',
    'HFC_NS' = 'HFC_NS',
    'HFC_SA' = 'HFC_SA',
    'SAT_BSS' = 'SAT_BSS',
    'SAT_NULL' = 'SAT_NULL',
    'SAT_C' = 'SAT_C',
    'SAT_CT' = 'SAT_CT',
    'SAT_SA' = 'SAT_SA',
}

export const ZReasonCode = () => z.nativeEnum(EReasonCode);