import { z } from "zod";

export enum ERoadTypeCode {
    AV = 'AV',     CL = 'CL',     CR = 'CR',     CT = 'CT',     DR = 'DR',     LANE = 'LANE',
    PDE = 'PDE',   PL = 'PL',     RD = 'RD',     ST = 'ST',     TCE = 'TCE',   WAY = 'WAY',
    ACCS = 'ACCS', ACRE = 'ACRE', ALLY = 'ALLY', AMBL = 'AMBL', APP = 'APP',   ARC = 'ARC',
    ARTL = 'ARTL', BA = 'BA',     BANK = 'BANK', BAY = 'BAY',   BCH = 'BCH',   BDGE = 'BDGE',
    BDWY = 'BDWY', BEND = 'BEND', BOWL = 'BOWL', BR = 'BR',     BRAE = 'BRAE', BRAN = 'BRAN',
    BRK = 'BRK',   BROW = 'BROW', BVD = 'BVD',   BVDE = 'BVDE', BWLK = 'BWLK', BYPA = 'BYPA',
    CCT = 'CCT',   CH = 'CH',     CIR = 'CIR',   CLR = 'CLR',   CLT = 'CLT',   CMMN = 'CMMN',
    CNR = 'CNR',   CNWY = 'CNWY', CON = 'CON',   COVE = 'COVE', CPS = 'CPS',   CRCS = 'CRCS',
    CRF = 'CRF',   CRK = 'CRK',   CRSE = 'CRSE', CRSG = 'CRSG', CRSS = 'CRSS', CRST = 'CRST',
    CSO = 'CSO',   CSWY = 'CSWY', CTR = 'CTR',   CTYD = 'CTYD', CUTT = 'CUTT', DALE = 'DALE',
    DE = 'DE',     DELL = 'DELL', DIV = 'DIV',   DOCK = 'DOCK', DOM = 'DOM',   DOWN = 'DOWN',
    DVWY = 'DVWY', DWNS = 'DWNS', EDGE = 'EDGE', ELB = 'ELB',   END = 'END',   ENT = 'ENT',
    ESMT = 'ESMT', ESP = 'ESP',   EST = 'EST',   EXP = 'EXP',   EXTN = 'EXTN', FAWY = 'FAWY',
    FITR = 'FITR', FLAT = 'FLAT', FOLW = 'FOLW', FORD = 'FORD', FORK = 'FORK', FRTG = 'FRTG',
    FSHR = 'FSHR', FTRK = 'FTRK', FTWY = 'FTWY', FWY = 'FWY',   GAP = 'GAP',   GDN = 'GDN',
    GDNS = 'GDNS', GLDE = 'GLDE', GLEN = 'GLEN', GLY = 'GLY',   GR = 'GR',     GRA = 'GRA',
    GRN = 'GRN',   GTE = 'GTE',   GWY = 'GWY',   HILL = 'HILL', HLLW = 'HLLW', HTH = 'HTH',
    HTS = 'HTS',   HUB = 'HUB',   HVN = 'HVN',   HWY = 'HWY',   ID = 'ID',     INLT = 'INLT',
    INTG = 'INTG', JNC = 'JNC',   KEY = 'KEY',   KEYS = 'KEYS', KNOL = 'KNOL', LDG = 'LDG',
    LINE = 'LINE', LINK = 'LINK', LKT = 'LKT',   LNWY = 'LNWY', LOOP = 'LOOP', LYNN = 'LYNN',
    MALL = 'MALL', MANR = 'MANR', MEAD = 'MEAD', MEWS = 'MEWS', MILE = 'MILE', MNDR = 'MNDR',
    NOOK = 'NOOK', OTLK = 'OTLK', OTLT = 'OTLT', PARK = 'PARK', PASS = 'PASS', PATH = 'PATH',
    PKT = 'PKT',   PLZA = 'PLZA', PNT = 'PNT',   PORT = 'PORT', PROM = 'PROM', PRST = 'PRST',
    PSGE = 'PSGE', PSLA = 'PSLA', PWAY = 'PWAY', PWY = 'PWY',   QDRT = 'QDRT', QY = 'QY',
    QYS = 'QYS',   RAMP = 'RAMP', RCH = 'RCH',   RDGE = 'RDGE', RDS = 'RDS',   RDWY = 'RDWY',
    REEF = 'REEF', RES = 'RES',   REST = 'REST', RIDE = 'RIDE', RING = 'RING', RISE = 'RISE',
    RMBL = 'RMBL', RND = 'RND',   ROFW = 'ROFW', ROW = 'ROW',   RSNG = 'RSNG', RTE = 'RTE',
    RTN = 'RTN',   RTT = 'RTT',   RUN = 'RUN',   RVR = 'RVR',   SBWY = 'SBWY', SLPE = 'SLPE',
    SPUR = 'SPUR', SQ = 'SQ',     STAI = 'STAI', STPS = 'STPS', STRA = 'STRA', STRP = 'STRP',
    SVWY = 'SVWY', TARN = 'TARN', THRU = 'THRU', TKWY = 'TKWY', TOP = 'TOP',   TOR = 'TOR',
    TRK = 'TRK',   TRL = 'TRL',   TURN = 'TURN', TWIST = 'TWIST', VALE = 'VALE', VIEW = 'VIEW',
    VLGE = 'VLGE', VLLA = 'VLLA', VLLY = 'VLLY', VSTA = 'VSTA', VWS = 'VWS',   WALK = 'WALK',
    WDS = 'WDS',   WHRF = 'WHRF', WKWY = 'WKWY', WTRS = 'WTRS', WYND = 'WYND',
    
}

export const ZRoadTypeCode = z.nativeEnum(ERoadTypeCode);